platform :ios, '9.0'

target 'ePotato' do

  use_frameworks!


  # Pods

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/AdMob'

  pod 'SQLite.swift', '~> 0.11.3'

  pod 'Toast-Swift', '~> 2.0.0'

  pod 'PhoneNumberKit', '~> 1.2'

  pod 'IQKeyboardManagerSwift'

  pod 'SelectionDialog'

end
