// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   potatoAPI/v1
// Description:
//   API for ePotato

#import "GTLRPotatoAPIObjects.h"
#import "GTLRPotatoAPIQuery.h"
#import "GTLRPotatoAPIService.h"
