// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   potatoAPI/v1
// Description:
//   API for ePotato

#import "GTLRPotatoAPIObjects.h"

// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_Id
//

@implementation GTLRPotatoAPI_Id
@dynamic identifier;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_IdCollection
//

@implementation GTLRPotatoAPI_IdCollection
@dynamic items;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRPotatoAPI_Id class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_Notice
//

@implementation GTLRPotatoAPI_Notice
@dynamic code, message, ok;
@end


// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_Potato
//

@implementation GTLRPotatoAPI_Potato
@dynamic dt, form, identifier, message, n, pid, uid;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
    return @{@"identifier": @"id"};
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_PotatoCollection
//

@implementation GTLRPotatoAPI_PotatoCollection
@dynamic items;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
    NSDictionary<NSString *, Class> *map = @{
            @"items": [GTLRPotatoAPI_Potato class]
    };
    return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_Profile
//

@implementation GTLRPotatoAPI_Profile
@dynamic contacts, epid, fiids, fiidsIos, followers, following, identifier, password, phone, potatoes, rand, strangers;

+ (NSDictionary<NSString *, NSString *> *)propertyToJSONKeyMap {
  return @{ @"identifier" : @"id" };
}

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"contacts" : [NSString class],
    @"fiids" : [NSString class],
    @"fiidsIos" : [NSString class],
    @"followers" : [NSString class],
          @"following": [NSString class],
          @"potatoes": [NSString class]
  };
  return map;
}

@end


// ----------------------------------------------------------------------------
//
//   GTLRPotatoAPI_ProfileCollection
//

@implementation GTLRPotatoAPI_ProfileCollection
@dynamic items;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"items" : [GTLRPotatoAPI_Profile class]
  };
  return map;
}

@end
