// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   potatoAPI/v1
// Description:
//   API for ePotato

#import "GTLRPotatoAPI.h"

// ----------------------------------------------------------------------------
// Authorization scope

NSString * const kGTLRAuthScopePotatoAPIUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";

// ----------------------------------------------------------------------------
//   GTLRPotatoAPIService
//

@implementation GTLRPotatoAPIService

- (instancetype)init {
  self = [super init];
  if (self) {
    // From discovery.
    self.rootURLString = @"https://e-potato.appspot.com/_ah/api/";
    self.servicePath = @"potatoAPI/v1/";
    self.batchPath = @"batch";
    self.prettyPrintQueryParameterNames = @[ @"prettyPrint" ];
  }
  return self;
}

@end
