// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   potatoAPI/v1
// Description:
//   API for ePotato

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRPotatoAPI_Id;
@class GTLRPotatoAPI_Potato;
@class GTLRPotatoAPI_Profile;

// Generated comments include content from the discovery document; avoid them
// causing warnings since clang's checks are some what arbitrary.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdocumentation"

NS_ASSUME_NONNULL_BEGIN

/**
 *  GTLRPotatoAPI_Id
 */
@interface GTLRPotatoAPI_Id : GTLRObject

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *identifier;

@end


/**
 *  GTLRPotatoAPI_IdCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRPotatoAPI_IdCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRPotatoAPI_Id *> *items;

@end


/**
 *  GTLRPotatoAPI_Notice
 */
@interface GTLRPotatoAPI_Notice : GTLRObject

/**
 *  code
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *code;

@property(nonatomic, copy, nullable) NSString *message;

/**
 *  ok
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *ok;

@end


/**
 *  GTLRPotatoAPI_Potato
 */
@interface GTLRPotatoAPI_Potato : GTLRObject

@property(nonatomic, copy, nullable) NSString *dt;

/**
 *  form
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *form;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *identifier;

@property(nonatomic, copy, nullable) NSString *message;

/**
 *  n
 *
 *  Uses NSNumber of intValue.
 */
@property(nonatomic, strong, nullable) NSNumber *n;

@property(nonatomic, copy, nullable) NSString *pid;
@property(nonatomic, copy, nullable) NSString *uid;

@end


/**
 *  GTLRPotatoAPI_PotatoCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRPotatoAPI_PotatoCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRPotatoAPI_Potato *> *items;

@end


/**
 *  GTLRPotatoAPI_Profile
 */
@interface GTLRPotatoAPI_Profile : GTLRObject

@property(nonatomic, strong, nullable) NSArray<NSString *> *contacts;
@property(nonatomic, copy, nullable) NSString *epid;
@property(nonatomic, strong, nullable) NSArray<NSString *> *fiids;
@property(nonatomic, strong, nullable) NSArray<NSString *> *fiidsIos;
@property(nonatomic, strong, nullable) NSArray<NSString *> *followers;
@property(nonatomic, strong, nullable) NSArray<NSString *> *following;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *identifier;

@property(nonatomic, copy, nullable) NSString *password;
@property(nonatomic, copy, nullable) NSString *phone;
@property(nonatomic, strong, nullable) NSArray<NSString *> *potatoes;

/**
 *  rand
 *
 *  Uses NSNumber of doubleValue.
 */
@property(nonatomic, strong, nullable) NSNumber *rand;

/**
 *  strangers
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *strangers;

@end


/**
 *  GTLRPotatoAPI_ProfileCollection
 *
 *  @note This class supports NSFastEnumeration and indexed subscripting over
 *        its "items" property.
 */
@interface GTLRPotatoAPI_ProfileCollection : GTLRCollectionObject

/**
 *  items
 *
 *  @note This property is used to support NSFastEnumeration and indexed
 *        subscripting on this class.
 */
@property(nonatomic, strong, nullable) NSArray<GTLRPotatoAPI_Profile *> *items;

@end

NS_ASSUME_NONNULL_END

#pragma clang diagnostic pop
